package bindings

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/grovetools/core/pkg/models"
	"github.com/grovetools/core/pkg/tmux/keygen"
)

// GroupBinding holds the resolved data needed to generate tmux bindings for one group.
type GroupBinding struct {
	Name     string                              // Group name ("default", "grovetools", etc.)
	Prefix   string                              // Tmux prefix string (e.g. "<prefix>", "<grove> k")
	Sessions map[string]models.NavSessionConfig  // Key → session config
}

// GenerateTmuxConf generates tmux key binding config files for all groups.
// binDir is the path to the grove bin directory (for nav binary references).
// cacheDir is the path to the grove cache directory (output location).
func GenerateTmuxConf(groups []GroupBinding, binDir, cacheDir string) error {
	navCacheDir := filepath.Join(cacheDir, "nav")
	if err := os.MkdirAll(navCacheDir, 0o755); err != nil {
		return fmt.Errorf("failed to create nav cache directory: %w", err)
	}

	var masterBindings strings.Builder
	masterBindings.WriteString("# Auto-generated nav workspace bindings\n")
	masterBindings.WriteString("# Generated by grove nav\n\n")

	for _, group := range groups {
		// Skip groups without a prefix — no keybindings to generate.
		if group.Prefix == "" {
			continue
		}

		tableName := "nav-workspaces"
		if group.Name != "default" {
			tableName = "nav-" + group.Name
		}

		cfg := keygen.Config{
			Prefix:    group.Prefix,
			TableName: tableName,
		}

		var bindings strings.Builder
		bindings.WriteString(fmt.Sprintf("# Group: %s\n", group.Name))
		bindings.WriteString(fmt.Sprintf("# Prefix mode: %s\n\n", group.Prefix))

		if group.Name == "default" {
			bindings.WriteString("# Hook to track session switches for history\n")
			bindings.WriteString(fmt.Sprintf("set-hook -g client-session-changed 'run-shell -b \"HOME=$HOME PATH=$PATH:%s nav record-session\"'\n\n", binDir))
		}

		entryPoint := cfg.GenerateEntryPoint()
		if len(entryPoint) > 0 {
			bindings.WriteString(strings.Join(entryPoint, "\n"))
			bindings.WriteString("\n")
		}

		helpCmd := "nav key list | less -R"
		if group.Name != "default" {
			helpCmd = fmt.Sprintf("nav key list --group %s | less -R", group.Name)
		}
		escapeHatches := cfg.GenerateEscapeHatches(helpCmd)
		if len(escapeHatches) > 0 {
			bindings.WriteString(strings.Join(escapeHatches, "\n"))
			bindings.WriteString("\n")
		}

		sessionizerPath := fmt.Sprintf("HOME=$HOME PATH=$PATH:%s nav sessionize", binDir)

		// Sort sessions by key for consistent output.
		keys := make([]string, 0, len(group.Sessions))
		for k := range group.Sessions {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		bindings.WriteString("# --- Workspace Bindings ---\n")
		for _, key := range keys {
			sess := group.Sessions[key]
			if sess.Path == "" {
				continue
			}
			comment := fmt.Sprintf("# %s: %s", key, filepath.Base(sess.Path))
			bindings.WriteString(comment + "\n")
			actionPart := fmt.Sprintf("run-shell \"%s '%s'\"", sessionizerPath, sess.Path)
			bindCmd := cfg.FormatBindKey(key, actionPart, "-r")
			bindings.WriteString(bindCmd + "\n\n")
		}

		if group.Name == "default" {
			masterBindings.WriteString(bindings.String())
		} else {
			groupFilename := fmt.Sprintf("generated-bindings-%s.conf", group.Name)
			groupFile := filepath.Join(navCacheDir, groupFilename)
			if err := os.WriteFile(groupFile, []byte(bindings.String()), 0o644); err != nil {
				return fmt.Errorf("failed to write group bindings file %s: %w", groupFilename, err)
			}
			masterBindings.WriteString(fmt.Sprintf("\n# Source group: %s\n", group.Name))
			masterBindings.WriteString(fmt.Sprintf("source-file %s\n", groupFile))
		}
	}

	masterFile := filepath.Join(navCacheDir, "generated-bindings.conf")
	return os.WriteFile(masterFile, []byte(masterBindings.String()), 0o644)
}
